export function renderDrawdownChartScript(): string {
  return [
    "function ddCompute(series, mode) {",
    "  const points = Array.isArray(series) ? series : [];",
    "  if (!points.length) {",
    "    return { series: [], maxDrawdownAbs: 0, maxDrawdownPct: 0 };",
    "  }",
    "",
    "  let runningPeak = -Infinity;",
    "  let maxDrawdownAbs = 0;",
    "  let maxDrawdownPct = 0;",
    "  const out = [];",
    "",
    "  for (const point of points) {",
    "    const value = mode === 'BTC' ? eqNumber(point.equityBtc, 0) : eqNumber(point.equityUsd, 0);",
    "    if (value > runningPeak) runningPeak = value;",
    "",
    "    const drawdownAbs = value - runningPeak;",
    "    const drawdownPct = runningPeak > 0 ? (drawdownAbs / runningPeak) * 100 : 0;",
    "",
    "    if (drawdownAbs < maxDrawdownAbs) maxDrawdownAbs = drawdownAbs;",
    "    if (drawdownPct < maxDrawdownPct) maxDrawdownPct = drawdownPct;",
    "",
    "    out.push({",
    "      ts: point.ts,",
    "      value,",
    "      peak: runningPeak,",
    "      drawdownAbs,",
    "      drawdownPct",
    "    });",
    "  }",
    "",
    "  return {",
    "    series: out,",
    "    maxDrawdownAbs,",
    "    maxDrawdownPct",
    "  };",
    "}",
    "",
    "function renderDrawdownPanel(state, equitySeriesWindow, equityMode) {",
    "  const mode = state.drawdownMode === 'pct' ? 'pct' : 'abs';",
    "  document.querySelectorAll('.drawdown-toggle-btn').forEach((btn) => {",
    "    const value = btn.getAttribute('data-dd-mode');",
    "    btn.classList.toggle('active', value === mode);",
    "  });",
    "",
    "  const computed = ddCompute(equitySeriesWindow, equityMode);",
    "  const maxAbsText = equityMode === 'BTC' ? eqFmtBtc(computed.maxDrawdownAbs, false) : eqFmtUsd(computed.maxDrawdownAbs);",
    "  const maxPctText = computed.maxDrawdownPct.toFixed(2) + '%';",
    "  text('drawdownSummary', 'Max DD: ' + maxAbsText + ' (' + maxPctText + ')');",
    "",
    "  renderDrawdownChartSvg(computed.series, mode, equityMode);",
    "}",
    "",
    "function renderDrawdownChartSvg(series, mode, equityMode) {",
    "  const svg = el('drawdownChart');",
    "  if (!svg) return;",
    "",
    "  if (!Array.isArray(series) || !series.length) {",
    "    svg.innerHTML = '<text x=\"20\" y=\"44\" fill=\"#8fa6c1\" font-family=\"IBM Plex Mono, Menlo, monospace\" font-size=\"14\">Awaiting drawdown data</text>';",
    "    return;",
    "  }",
    "",
    "  const values = series.map((row) => mode === 'pct' ? eqNumber(row.drawdownPct, 0) : eqNumber(row.drawdownAbs, 0));",
    "  let min = Math.min.apply(null, values);",
    "  let max = Math.max.apply(null, values);",
    "  if (min === max) { min -= 1; max += 1; }",
    "",
    "  const W = 1200;",
    "  const H = 180;",
    "  const PADX = 56;",
    "  const PADY = 20;",
    "  const range = Math.max(1e-9, max - min);",
    "  const xSpan = Math.max(1, series.length - 1);",
    "  const x = (idx) => PADX + (idx / xSpan) * (W - PADX * 2);",
    "  const y = (val) => H - PADY - ((val - min) / range) * (H - PADY * 2);",
    "",
    "  let path = '';",
    "  for (let i = 0; i < values.length; i += 1) {",
    "    path += (i === 0 ? 'M ' : ' L ') + x(i).toFixed(2) + ' ' + y(values[i]).toFixed(2);",
    "  }",
    "",
    "  const yZero = y(0).toFixed(2);",
    "  const maxLabel = mode === 'pct' ? max.toFixed(2) + '%' : (equityMode === 'BTC' ? eqFmtBtc(max, false) : eqFmtUsd(max));",
    "  const minLabel = mode === 'pct' ? min.toFixed(2) + '%' : (equityMode === 'BTC' ? eqFmtBtc(min, false) : eqFmtUsd(min));",
    "",
    "  svg.innerHTML =",
    "    '<line x1=\"' + PADX + '\" y1=\"' + yZero + '\" x2=\"' + (W - PADX) + '\" y2=\"' + yZero + '\" stroke=\"rgba(255,255,255,0.20)\" stroke-width=\"1\" />' +",
    "    '<path d=\"' + path + '\" fill=\"none\" stroke=\"#ff6d7c\" stroke-width=\"2\" />' +",
    "    '<text x=\"' + (PADX + 6) + '\" y=\"' + (PADY + 12) + '\" fill=\"#8fa6c1\" font-family=\"IBM Plex Mono, Menlo, monospace\" font-size=\"11\">max ' + maxLabel + '</text>' +",
    "    '<text x=\"' + (PADX + 6) + '\" y=\"' + (H - 8) + '\" fill=\"#8fa6c1\" font-family=\"IBM Plex Mono, Menlo, monospace\" font-size=\"11\">min ' + minLabel + '</text>';",
    "}",
    ""
  ].join("\n");
}
