export function renderDrawdownChartScript(): string {
  return [
    "function computeDrawdownSeries(series, field) {",
    "  const points = Array.isArray(series) ? series : [];",
    "  if (!points.length) return [];",
    "",
    "  let runningPeak = -Infinity;",
    "  const out = [];",
    "",
    "  for (const row of points) {",
    "    const value = eqNumber(row && row[field], Number.NaN);",
    "    const ts = eqNumber(row && row.ts, Number.NaN);",
    "    if (!Number.isFinite(value) || !Number.isFinite(ts)) continue;",
    "",
    "    if (value > runningPeak) runningPeak = value;",
    "    const ddAbs = value - runningPeak;",
    "    const ddPct = runningPeak > 0 ? (ddAbs / runningPeak) * 100 : 0;",
    "",
    "    out.push({ ts, value, peak: runningPeak, ddAbs, ddPct });",
    "  }",
    "",
    "  return out;",
    "}",
    "",
    "function renderDrawdownChart(svgEl, series, field, ddMode, formatter) {",
    "  const drawdownSeries = computeDrawdownSeries(series, field);",
    "  const safeFormatter = formatter && typeof formatter === 'object' ? formatter : {};",
    "",
    "  if (!svgEl) {",
    "    return { maxDdAbs: 0, maxDdPct: 0 };",
    "  }",
    "",
    "  if (!drawdownSeries.length) {",
    "    svgEl.innerHTML = '<text x=\"20\" y=\"44\" fill=\"#8fa6c1\" font-family=\"IBM Plex Mono, Menlo, monospace\" font-size=\"14\">No drawdown data yet</text>';",
    "    return { maxDdAbs: 0, maxDdPct: 0 };",
    "  }",
    "",
    "  let maxDdAbs = 0;",
    "  let maxDdPct = 0;",
    "  for (const row of drawdownSeries) {",
    "    if (Number.isFinite(row.ddAbs) && row.ddAbs < maxDdAbs) maxDdAbs = row.ddAbs;",
    "    if (Number.isFinite(row.ddPct) && row.ddPct < maxDdPct) maxDdPct = row.ddPct;",
    "  }",
    "",
    "  const usePct = String(ddMode || 'abs').toLowerCase() === 'pct';",
    "  const values = drawdownSeries.map((row) => (usePct ? row.ddPct : row.ddAbs));",
    "  let min = Math.min.apply(null, values);",
    "  let max = Math.max.apply(null, values);",
    "",
    "  if (!Number.isFinite(min) || !Number.isFinite(max)) {",
    "    svgEl.innerHTML = '<text x=\"20\" y=\"44\" fill=\"#8fa6c1\" font-family=\"IBM Plex Mono, Menlo, monospace\" font-size=\"14\">No drawdown data yet</text>';",
    "    return { maxDdAbs, maxDdPct };",
    "  }",
    "",
    "  if (min === max) {",
    "    min -= 1;",
    "    max += 1;",
    "  }",
    "",
    "  const W = 1200;",
    "  const H = 180;",
    "  const PADX = 56;",
    "  const PADY = 20;",
    "  const xSpan = Math.max(1, values.length - 1);",
    "  const range = Math.max(1e-9, max - min);",
    "",
    "  const x = (i) => PADX + (i / xSpan) * (W - PADX * 2);",
    "  const y = (v) => H - PADY - ((v - min) / range) * (H - PADY * 2);",
    "",
    "  let path = '';",
    "  for (let i = 0; i < values.length; i += 1) {",
    "    path += (i === 0 ? 'M ' : ' L ') + x(i).toFixed(2) + ' ' + y(values[i]).toFixed(2);",
    "  }",
    "",
    "  const zeroY = y(0).toFixed(2);",
    "  const formatAbs = typeof safeFormatter.abs === 'function' ? safeFormatter.abs : (v) => String(v);",
    "  const formatPct = typeof safeFormatter.pct === 'function' ? safeFormatter.pct : (v) => String(v.toFixed(2) + '%');",
    "  const maxLabel = usePct ? formatPct(max) : formatAbs(max);",
    "  const minLabel = usePct ? formatPct(min) : formatAbs(min);",
    "",
    "  svgEl.innerHTML =",
    "    '<line x1=\"' + PADX + '\" y1=\"' + zeroY + '\" x2=\"' + (W - PADX) + '\" y2=\"' + zeroY + '\" stroke=\"rgba(255,255,255,0.20)\" stroke-width=\"1\" />' +",
    "    '<path d=\"' + path + '\" fill=\"none\" stroke=\"#ff6d7c\" stroke-width=\"2\" />' +",
    "    '<text x=\"' + (PADX + 6) + '\" y=\"' + (PADY + 12) + '\" fill=\"#8fa6c1\" font-family=\"IBM Plex Mono, Menlo, monospace\" font-size=\"11\">max ' + maxLabel + '</text>' +",
    "    '<text x=\"' + (PADX + 6) + '\" y=\"' + (H - 8) + '\" fill=\"#8fa6c1\" font-family=\"IBM Plex Mono, Menlo, monospace\" font-size=\"11\">min ' + minLabel + '</text>';",
    "",
    "  return { maxDdAbs, maxDdPct };",
    "}",
    ""
  ].join("\n");
}
