export function renderEquityChartScript(): string {
  return [
    "function eqWindowMs(key) {",
    "  const map = {",
    "    '15m': 15 * 60 * 1000,",
    "    '1h': 60 * 60 * 1000,",
    "    '4h': 4 * 60 * 60 * 1000,",
    "    '12h': 12 * 60 * 60 * 1000,",
    "    '24h': 24 * 60 * 60 * 1000",
    "  };",
    "  return map[key] || map['24h'];",
    "}",
    "",
    "function eqFilterByWindow(series, key) {",
    "  const list = Array.isArray(series) ? series : [];",
    "  const cutoff = Date.now() - eqWindowMs(key);",
    "  return list.filter((row) => eqNumber(row && row.ts, 0) >= cutoff);",
    "}",
    "",
    "function eqFmtUsd(v) {",
    "  const value = Number(v);",
    "  if (!Number.isFinite(value)) return '-';",
    "  return '$' + value.toFixed(2);",
    "}",
    "",
    "function eqFmtBtc(v, compact) {",
    "  const value = Number(v);",
    "  if (!Number.isFinite(value)) return '-';",
    "  return value.toFixed(compact ? 6 : 8);",
    "}",
    "",
    "function eqTimeShort(ts) {",
    "  if (!ts) return '-';",
    "  return new Date(ts).toLocaleTimeString('en-US', { hour12: false });",
    "}",
    "",
    "function eqTimeLong(ts) {",
    "  if (!ts) return '-';",
    "  return new Date(ts).toLocaleString('en-US', { hour12: false });",
    "}",
    "",
    "function eqFieldForMode(mode) {",
    "  return mode === 'BTC' ? 'equityBtc' : 'equityUsd';",
    "}",
    "",
    "function eqRenderLineChart(svg, series, field, mode) {",
    "  if (!svg) return;",
    "  if (!Array.isArray(series) || series.length < 2) {",
    "    svg.innerHTML = '<text x=\"20\" y=\"44\" fill=\"#8fa6c1\" font-family=\"IBM Plex Mono, Menlo, monospace\" font-size=\"15\">Awaiting data</text>';",
    "    return;",
    "  }",
    "",
    "  const W = 1200;",
    "  const H = 300;",
    "  const PADX = 56;",
    "  const PADY = 28;",
    "  const values = series.map((row) => eqNumber(row && row[field], Number.NaN));",
    "",
    "  let min = Math.min.apply(null, values);",
    "  let max = Math.max.apply(null, values);",
    "  if (!Number.isFinite(min) || !Number.isFinite(max)) {",
    "    svg.innerHTML = '<text x=\"20\" y=\"44\" fill=\"#8fa6c1\" font-family=\"IBM Plex Mono, Menlo, monospace\" font-size=\"15\">Awaiting data</text>';",
    "    return;",
    "  }",
    "  if (min === max) { min -= 1; max += 1; }",
    "",
    "  const xSpan = Math.max(1, series.length - 1);",
    "  const range = Math.max(1e-9, max - min);",
    "  const x = (i) => PADX + (i / xSpan) * (W - PADX * 2);",
    "  const y = (v) => H - PADY - ((v - min) / range) * (H - PADY * 2);",
    "",
    "  let line = '';",
    "  for (let i = 0; i < values.length; i += 1) {",
    "    line += (i === 0 ? 'M ' : ' L ') + x(i).toFixed(2) + ' ' + y(values[i]).toFixed(2);",
    "  }",
    "",
    "  const area =",
    "    line +",
    "    ' L ' + x(values.length - 1).toFixed(2) + ' ' + y(min).toFixed(2) +",
    "    ' L ' + x(0).toFixed(2) + ' ' + y(min).toFixed(2) +",
    "    ' Z';",
    "",
    "  const last = values[values.length - 1];",
    "  const lastX = x(values.length - 1).toFixed(2);",
    "  const lastY = y(last).toFixed(2);",
    "  const maxLabel = mode === 'BTC' ? eqFmtBtc(max, false) + ' BTC' : eqFmtUsd(max);",
    "  const minLabel = mode === 'BTC' ? eqFmtBtc(min, false) + ' BTC' : eqFmtUsd(min);",
    "",
    "  svg.innerHTML =",
    "    '<path d=\"' + area + '\" fill=\"rgba(55,180,255,0.15)\" />' +",
    "    '<path d=\"' + line + '\" fill=\"none\" stroke=\"#37b4ff\" stroke-width=\"3\" stroke-linecap=\"round\" />' +",
    "    '<circle cx=\"' + lastX + '\" cy=\"' + lastY + '\" r=\"4\" fill=\"#37b4ff\" />' +",
    "    '<text x=\"' + (PADX + 6) + '\" y=\"' + (y(max) - 8).toFixed(2) + '\" fill=\"#8fa6c1\" font-family=\"IBM Plex Mono, Menlo, monospace\" font-size=\"12\">max ' + maxLabel + '</text>' +",
    "    '<text x=\"' + (PADX + 6) + '\" y=\"' + (y(min) - 8).toFixed(2) + '\" fill=\"#8fa6c1\" font-family=\"IBM Plex Mono, Menlo, monospace\" font-size=\"12\">min ' + minLabel + '</text>';",
    "}",
    "",
    "function eqRenderComposition(svg, series) {",
    "  if (!svg) return;",
    "  if (!Array.isArray(series) || series.length < 2) {",
    "    svg.innerHTML = '<text x=\"20\" y=\"44\" fill=\"#8fa6c1\" font-family=\"IBM Plex Mono, Menlo, monospace\" font-size=\"14\">Awaiting data</text>';",
    "    return;",
    "  }",
    "",
    "  const W = 1200;",
    "  const H = 180;",
    "  const PADX = 56;",
    "  const PADY = 20;",
    "  const usd = series.map((row) => eqNumber(row && row.usd_total, 0));",
    "  const btcUsd = series.map((row) => eqNumber(row && row.btcNotionalUsd, 0));",
    "  const values = usd.concat(btcUsd);",
    "",
    "  let min = Math.min.apply(null, values);",
    "  let max = Math.max.apply(null, values);",
    "  if (min === max) { min -= 1; max += 1; }",
    "",
    "  const xSpan = Math.max(1, usd.length - 1);",
    "  const range = Math.max(1e-9, max - min);",
    "  const x = (i) => PADX + (i / xSpan) * (W - PADX * 2);",
    "  const y = (v) => H - PADY - ((v - min) / range) * (H - PADY * 2);",
    "",
    "  let usdPath = '';",
    "  let btcPath = '';",
    "  for (let i = 0; i < usd.length; i += 1) {",
    "    usdPath += (i === 0 ? 'M ' : ' L ') + x(i).toFixed(2) + ' ' + y(usd[i]).toFixed(2);",
    "    btcPath += (i === 0 ? 'M ' : ' L ') + x(i).toFixed(2) + ' ' + y(btcUsd[i]).toFixed(2);",
    "  }",
    "",
    "  svg.innerHTML =",
    "    '<path d=\"' + usdPath + '\" fill=\"none\" stroke=\"#37b4ff\" stroke-width=\"2\" />' +",
    "    '<path d=\"' + btcPath + '\" fill=\"none\" stroke=\"#21e3a2\" stroke-width=\"2\" />' +",
    "    '<text x=\"' + (PADX + 6) + '\" y=\"' + (PADY + 12) + '\" fill=\"#8fa6c1\" font-family=\"IBM Plex Mono, Menlo, monospace\" font-size=\"11\">max ' + eqFmtUsd(max) + '</text>' +",
    "    '<text x=\"' + (PADX + 6) + '\" y=\"' + (H - 8) + '\" fill=\"#8fa6c1\" font-family=\"IBM Plex Mono, Menlo, monospace\" font-size=\"11\">min ' + eqFmtUsd(min) + '</text>';",
    "}",
    "",
    "function eqAttachTooltip(svg, tooltipEl, series, field, mode) {",
    "  if (!svg || !tooltipEl || !Array.isArray(series) || series.length < 2) {",
    "    if (tooltipEl) tooltipEl.style.display = 'none';",
    "    return;",
    "  }",
    "",
    "  const shell = el('equityChartShell');",
    "  const W = 1200;",
    "  const PADX = 56;",
    "  const plotWidth = W - PADX * 2;",
    "",
    "  svg.onmousemove = (event) => {",
    "    if (!shell) return;",
    "    const svgRect = svg.getBoundingClientRect();",
    "    if (svgRect.width <= 0) return;",
    "",
    "    const localX = event.clientX - svgRect.left;",
    "    const ratio = Math.min(1, Math.max(0, (localX / svgRect.width)));",
    "    const plotRatio = Math.min(1, Math.max(0, ((ratio * W) - PADX) / Math.max(1, plotWidth)));",
    "    const idx = Math.max(0, Math.min(series.length - 1, Math.round(plotRatio * (series.length - 1))));",
    "    const row = series[idx];",
    "",
    "    const equityValue = eqNumber(row && row[field], 0);",
    "    const textValue =",
    "      mode === 'BTC' ? eqFmtBtc(equityValue, false) + ' BTC' : eqFmtUsd(equityValue);",
    "",
    "    const shellRect = shell.getBoundingClientRect();",
    "    const idealLeft = event.clientX - shellRect.left + 10;",
    "    const idealTop = event.clientY - shellRect.top - 10;",
    "    const clampedLeft = Math.max(10, Math.min(shellRect.width - 220, idealLeft));",
    "    const clampedTop = Math.max(10, Math.min(shellRect.height - 10, idealTop));",
    "",
    "    tooltipEl.style.display = 'block';",
    "    tooltipEl.style.left = clampedLeft + 'px';",
    "    tooltipEl.style.top = clampedTop + 'px';",
    "    tooltipEl.innerHTML =",
    "      '<div><strong>' + escapeHtml(eqTimeLong(eqNumber(row && row.ts, 0))) + '</strong></div>' +",
    "      '<div>equity: ' + escapeHtml(textValue) + '</div>' +",
    "      '<div>mid: ' + escapeHtml(eqNumber(row && row.mid, 0).toFixed(2)) + '</div>' +",
    "      '<div>usd_total: ' + escapeHtml(eqNumber(row && row.usd_total, 0).toFixed(2)) + '</div>' +",
    "      '<div>btc_total: ' + escapeHtml(eqNumber(row && row.btc_total, 0).toFixed(8)) + '</div>' +",
    "      '<div>btcNotionalUsd: ' + escapeHtml(eqFmtUsd(eqNumber(row && row.btcNotionalUsd, 0))) + '</div>';",
    "  };",
    "",
    "  svg.onmouseleave = () => {",
    "    tooltipEl.style.display = 'none';",
    "  };",
    "}",
    "",
    "function renderEquityPanel(state) {",
    "  const mode = state && state.equityMode === 'BTC' ? 'BTC' : 'USD';",
    "  const windowKey = state && typeof state.equityWindow === 'string' ? state.equityWindow : '24h';",
    "  const drawdownMode = state && state.drawdownMode === 'pct' ? 'pct' : 'abs';",
    "",
    "  const fullSeries = Array.isArray(state && state.equitySeries) ? state.equitySeries : [];",
    "  const filteredSeries = eqFilterByWindow(fullSeries, windowKey);",
    "  const field = eqFieldForMode(mode);",
    "",
    "  document.querySelectorAll('.equity-toggle-btn').forEach((btn) => {",
    "    btn.classList.toggle('active', btn.getAttribute('data-equity-mode') === mode);",
    "  });",
    "  document.querySelectorAll('.equity-window-btn').forEach((btn) => {",
    "    btn.classList.toggle('active', btn.getAttribute('data-equity-window') === windowKey);",
    "  });",
    "  document.querySelectorAll('.drawdown-toggle-btn').forEach((btn) => {",
    "    btn.classList.toggle('active', btn.getAttribute('data-dd-mode') === drawdownMode);",
    "  });",
    "",
    "  const equitySvg = el('equityChart');",
    "  const compSvg = el('compositionChart');",
    "  const ddSvg = el('drawdownChart');",
    "  const tooltip = el('equityTooltip');",
    "",
    "  if (filteredSeries.length < 2) {",
    "    text('equityNow', '-');",
    "    text('equityRange', '-');",
    "    text('equitySpan', '-');",
    "    text('compositionLegend', '-');",
    "    text('drawdownSummary', 'Max DD: -');",
    "    eqRenderLineChart(equitySvg, [], field, mode);",
    "    eqRenderComposition(compSvg, []);",
    "    if (typeof renderDrawdownChart === 'function') {",
    "      renderDrawdownChart(ddSvg, [], field, drawdownMode, {});",
    "    }",
    "    if (tooltip) tooltip.style.display = 'none';",
    "    return;",
    "  }",
    "",
    "  const values = filteredSeries.map((row) => eqNumber(row && row[field], Number.NaN));",
    "  const min = Math.min.apply(null, values);",
    "  const max = Math.max.apply(null, values);",
    "  const last = filteredSeries[filteredSeries.length - 1];",
    "  const lastValue = eqNumber(last && last[field], 0);",
    "",
    "  const nowText =",
    "    mode === 'BTC' ? 'Equity ' + eqFmtBtc(lastValue, true) + ' BTC' : 'Equity ' + eqFmtUsd(lastValue);",
    "  const rangeText =",
    "    mode === 'BTC'",
    "      ? 'BTC range ' + eqFmtBtc(min, true) + '..' + eqFmtBtc(max, true)",
    "      : 'USD range ' + eqFmtUsd(min) + '..' + eqFmtUsd(max);",
    "  const spanText =",
    "    eqTimeShort(eqNumber(filteredSeries[0] && filteredSeries[0].ts, 0)) +",
    "    ' to ' +",
    "    eqTimeShort(eqNumber(last && last.ts, 0));",
    "",
    "  text('equityNow', nowText);",
    "  text('equityRange', rangeText);",
    "  text('equitySpan', spanText);",
    "  text(",
    "    'compositionLegend',",
    "    'USD total ' + eqFmtUsd(eqNumber(last && last.usd_total, 0)) +",
    "      ' | BTC notional ' + eqFmtUsd(eqNumber(last && last.btcNotionalUsd, 0))",
    "  );",
    "",
    "  eqRenderLineChart(equitySvg, filteredSeries, field, mode);",
    "  eqRenderComposition(compSvg, filteredSeries);",
    "  eqAttachTooltip(equitySvg, tooltip, filteredSeries, field, mode);",
    "",
    "  if (typeof renderDrawdownChart === 'function') {",
    "    const ddResult = renderDrawdownChart(ddSvg, filteredSeries, field, drawdownMode, {",
    "      abs: (v) => (mode === 'BTC' ? eqFmtBtc(v, false) + ' BTC' : eqFmtUsd(v)),",
    "      pct: (v) => Number(v).toFixed(2) + '%'",
    "    });",
    "    const abs = mode === 'BTC' ? eqFmtBtc(ddResult.maxDdAbs, false) + ' BTC' : eqFmtUsd(ddResult.maxDdAbs);",
    "    const pct = Number(ddResult.maxDdPct).toFixed(2) + '%';",
    "    text('drawdownSummary', 'Max DD: ' + abs + ' (' + pct + ')');",
    "  }",
    "}",
    ""
  ].join("\n");
}
