export function renderEquityChartScript(): string {
  return [
    "const EQUITY_WINDOWS = ['24h', '12h', '4h', '1h', '15m'];",
    "",
    "function eqFmtUsd(value) {",
    "  const parsed = Number(value);",
    "  if (!Number.isFinite(parsed)) return '-';",
    "  return '$' + parsed.toFixed(2);",
    "}",
    "",
    "function eqFmtBtc(value, compact) {",
    "  const parsed = Number(value);",
    "  if (!Number.isFinite(parsed)) return '-';",
    "  return parsed.toFixed(compact ? 6 : 8) + ' BTC';",
    "}",
    "",
    "function eqFormatShortTime(value) {",
    "  if (!value) return '-';",
    "  return new Date(value).toLocaleTimeString('en-US', { hour12: false });",
    "}",
    "",
    "function eqFormatLongTime(value) {",
    "  if (!value) return '-';",
    "  return new Date(value).toLocaleString('en-US', { hour12: false });",
    "}",
    "",
    "function eqValue(point, mode) {",
    "  if (!point || typeof point !== 'object') return 0;",
    "  return mode === 'BTC' ? eqNumber(point.equityBtc, 0) : eqNumber(point.equityUsd, 0);",
    "}",
    "",
    "function renderEquityPanel(state) {",
    "  const mode = state.equityMode === 'BTC' ? 'BTC' : 'USD';",
    "  const windowKey = EQUITY_WINDOWS.includes(state.equityWindow) ? state.equityWindow : '24h';",
    "  const allSeries = Array.isArray(state.equitySeries) ? state.equitySeries : [];",
    "  const series = eqFilterByWindow(allSeries, windowKey);",
    "",
    "  document.querySelectorAll('.equity-toggle-btn').forEach((btn) => {",
    "    const value = btn.getAttribute('data-equity-mode');",
    "    btn.classList.toggle('active', value === mode);",
    "  });",
    "",
    "  document.querySelectorAll('.equity-window-btn').forEach((btn) => {",
    "    const value = btn.getAttribute('data-equity-window');",
    "    btn.classList.toggle('active', value === windowKey);",
    "  });",
    "",
    "  if (!series.length) {",
    "    text('equityNow', 'Awaiting data');",
    "    text('equityRange', mode + ' range -');",
    "    text('equitySpan', '-');",
    "    renderEquityChartSvg([], mode);",
    "    renderCompositionChartSvg([]);",
    "    renderDrawdownPanel(state, [], mode);",
    "    return;",
    "  }",
    "",
    "  const values = series.map((point) => eqValue(point, mode));",
    "  const min = Math.min.apply(null, values);",
    "  const max = Math.max.apply(null, values);",
    "  const latest = values[values.length - 1];",
    "  const startTs = series[0].ts;",
    "  const endTs = series[series.length - 1].ts;",
    "",
    "  text('equityNow', mode === 'BTC' ? eqFmtBtc(latest, true) : eqFmtUsd(latest));",
    "  text(",
    "    'equityRange',",
    "    mode + ' range ' +",
    "      (mode === 'BTC'",
    "        ? eqFmtBtc(min, true) + ' to ' + eqFmtBtc(max, true)",
    "        : eqFmtUsd(min) + ' to ' + eqFmtUsd(max))",
    "  );",
    "  text('equitySpan', eqFormatShortTime(startTs) + ' to ' + eqFormatShortTime(endTs));",
    "",
    "  renderEquityChartSvg(series, mode);",
    "  renderCompositionChartSvg(series);",
    "  renderDrawdownPanel(state, series, mode);",
    "}",
    "",
    "function renderEquityChartSvg(series, mode) {",
    "  const svg = el('equityChart');",
    "  const tooltip = el('equityTooltip');",
    "  const shell = el('equityChartShell');",
    "  if (!svg) return;",
    "",
    "  if (!Array.isArray(series) || !series.length) {",
    "    svg.innerHTML = '<text x=\"20\" y=\"44\" fill=\"#8fa6c1\" font-family=\"IBM Plex Mono, Menlo, monospace\" font-size=\"15\">Awaiting equity data</text>';",
    "    if (tooltip) tooltip.style.display = 'none';",
    "    return;",
    "  }",
    "",
    "  const W = 1200;",
    "  const H = 300;",
    "  const PADX = 56;",
    "  const PADY = 28;",
    "  const values = series.map((point) => eqValue(point, mode));",
    "  let min = Math.min.apply(null, values);",
    "  let max = Math.max.apply(null, values);",
    "  if (min === max) { min -= 1; max += 1; }",
    "  const range = Math.max(1e-9, max - min);",
    "  const xSpan = Math.max(1, series.length - 1);",
    "",
    "  const x = (idx) => PADX + (idx / xSpan) * (W - PADX * 2);",
    "  const y = (val) => H - PADY - ((val - min) / range) * (H - PADY * 2);",
    "  const lastValue = values[values.length - 1];",
    "",
    "  let line = '';",
    "  for (let i = 0; i < series.length; i += 1) {",
    "    line += (i === 0 ? 'M ' : ' L ') + x(i).toFixed(2) + ' ' + y(values[i]).toFixed(2);",
    "  }",
    "",
    "  const yBase = y(min);",
    "  const area =",
    "    line +",
    "    ' L ' + x(series.length - 1).toFixed(2) + ' ' + yBase.toFixed(2) +",
    "    ' L ' + x(0).toFixed(2) + ' ' + yBase.toFixed(2) +",
    "    ' Z';",
    "",
    "  const maxY = y(max).toFixed(2);",
    "  const minY = y(min).toFixed(2);",
    "  const lastX = x(series.length - 1).toFixed(2);",
    "  const lastY = y(lastValue).toFixed(2);",
    "",
    "  svg.innerHTML =",
    "    '<line x1=\"' + PADX + '\" y1=\"' + maxY + '\" x2=\"' + (W - PADX) + '\" y2=\"' + maxY + '\" stroke=\"rgba(255,255,255,0.08)\" stroke-width=\"1\" />' +",
    "    '<line x1=\"' + PADX + '\" y1=\"' + minY + '\" x2=\"' + (W - PADX) + '\" y2=\"' + minY + '\" stroke=\"rgba(255,255,255,0.08)\" stroke-width=\"1\" />' +",
    "    '<path d=\"' + area + '\" fill=\"rgba(55,180,255,0.15)\" />' +",
    "    '<path d=\"' + line + '\" fill=\"none\" stroke=\"#37b4ff\" stroke-width=\"3\" stroke-linecap=\"round\" />' +",
    "    '<circle cx=\"' + lastX + '\" cy=\"' + lastY + '\" r=\"4\" fill=\"#37b4ff\" />' +",
    "    '<text x=\"' + (PADX + 6) + '\" y=\"' + (Number(maxY) - 8) + '\" fill=\"#8fa6c1\" font-family=\"IBM Plex Mono, Menlo, monospace\" font-size=\"12\">max ' + (mode === 'BTC' ? eqFmtBtc(max, false) : eqFmtUsd(max)) + '</text>' +",
    "    '<text x=\"' + (PADX + 6) + '\" y=\"' + (Number(minY) - 8) + '\" fill=\"#8fa6c1\" font-family=\"IBM Plex Mono, Menlo, monospace\" font-size=\"12\">min ' + (mode === 'BTC' ? eqFmtBtc(min, false) : eqFmtUsd(min)) + '</text>' +",
    "    '<rect id=\"equityHitbox\" x=\"' + PADX + '\" y=\"0\" width=\"' + (W - PADX * 2) + '\" height=\"' + H + '\" fill=\"transparent\" />';",
    "",
    "  const hitbox = el('equityHitbox');",
    "  if (!hitbox || !tooltip || !shell) return;",
    "",
    "  hitbox.onmousemove = (evt) => {",
    "    const rect = hitbox.getBoundingClientRect();",
    "    if (rect.width <= 0) return;",
    "    const ratio = Math.min(1, Math.max(0, (evt.clientX - rect.left) / rect.width));",
    "    const idx = Math.max(0, Math.min(series.length - 1, Math.round(ratio * (series.length - 1))));",
    "    const point = series[idx];",
    "    const selected = eqValue(point, mode);",
    "    const shellRect = shell.getBoundingClientRect();",
    "    const left = Math.min(shellRect.width - 16, Math.max(16, evt.clientX - shellRect.left + 12));",
    "    const top = Math.max(16, evt.clientY - shellRect.top - 8);",
    "",
    "    tooltip.style.display = 'block';",
    "    tooltip.style.left = left + 'px';",
    "    tooltip.style.top = top + 'px';",
    "    tooltip.innerHTML =",
    "      '<div><strong>' + escapeHtml(eqFormatLongTime(point.ts)) + '</strong></div>' +",
    "      '<div>equity: ' + escapeHtml(mode === 'BTC' ? eqFmtBtc(selected, false) : eqFmtUsd(selected)) + '</div>' +",
    "      '<div>mid: ' + escapeHtml(eqNumber(point.mid, 0).toFixed(2)) + '</div>' +",
    "      '<div>usd_total: ' + escapeHtml(eqNumber(point.usd_total, 0).toFixed(2)) + '</div>' +",
    "      '<div>btc_total: ' + escapeHtml(eqNumber(point.btc_total, 0).toFixed(8)) + '</div>';",
    "  };",
    "",
    "  hitbox.onmouseleave = () => {",
    "    tooltip.style.display = 'none';",
    "  };",
    "}",
    "",
    "function renderCompositionChartSvg(series) {",
    "  const svg = el('compositionChart');",
    "  const legend = el('compositionLegend');",
    "  if (!svg) return;",
    "",
    "  if (!Array.isArray(series) || !series.length) {",
    "    svg.innerHTML = '<text x=\"20\" y=\"44\" fill=\"#8fa6c1\" font-family=\"IBM Plex Mono, Menlo, monospace\" font-size=\"14\">Awaiting composition data</text>';",
    "    if (legend) legend.textContent = 'USD total - | BTC notional -';",
    "    return;",
    "  }",
    "",
    "  const W = 1200;",
    "  const H = 180;",
    "  const PADX = 56;",
    "  const PADY = 20;",
    "  const usdSeries = series.map((point) => eqNumber(point.usd_total, 0));",
    "  const btcUsdSeries = series.map((point) => eqNumber(point.btcNotionalUsd, 0));",
    "  const all = usdSeries.concat(btcUsdSeries);",
    "  let min = Math.min.apply(null, all);",
    "  let max = Math.max.apply(null, all);",
    "  if (min === max) { min -= 1; max += 1; }",
    "  const range = Math.max(1e-9, max - min);",
    "  const xSpan = Math.max(1, series.length - 1);",
    "",
    "  const x = (idx) => PADX + (idx / xSpan) * (W - PADX * 2);",
    "  const y = (val) => H - PADY - ((val - min) / range) * (H - PADY * 2);",
    "",
    "  let usdPath = '';",
    "  let btcPath = '';",
    "  for (let i = 0; i < series.length; i += 1) {",
    "    usdPath += (i === 0 ? 'M ' : ' L ') + x(i).toFixed(2) + ' ' + y(usdSeries[i]).toFixed(2);",
    "    btcPath += (i === 0 ? 'M ' : ' L ') + x(i).toFixed(2) + ' ' + y(btcUsdSeries[i]).toFixed(2);",
    "  }",
    "",
    "  svg.innerHTML =",
    "    '<path d=\"' + usdPath + '\" fill=\"none\" stroke=\"#37b4ff\" stroke-width=\"2\" />' +",
    "    '<path d=\"' + btcPath + '\" fill=\"none\" stroke=\"#21e3a2\" stroke-width=\"2\" />' +",
    "    '<text x=\"' + (PADX + 6) + '\" y=\"' + (PADY + 12) + '\" fill=\"#8fa6c1\" font-family=\"IBM Plex Mono, Menlo, monospace\" font-size=\"11\">max ' + eqFmtUsd(max) + '</text>' +",
    "    '<text x=\"' + (PADX + 6) + '\" y=\"' + (H - 8) + '\" fill=\"#8fa6c1\" font-family=\"IBM Plex Mono, Menlo, monospace\" font-size=\"11\">min ' + eqFmtUsd(min) + '</text>';",
    "",
    "  if (legend) {",
    "    legend.textContent =",
    "      'USD total ' + eqFmtUsd(usdSeries[usdSeries.length - 1]) +",
    "      ' | BTC notional (USD) ' + eqFmtUsd(btcUsdSeries[btcUsdSeries.length - 1]);",
    "  }",
    "}",
    ""
  ].join("\n");
}
