export function renderUseEquitySeriesScript(opts: {
  maxEquityPointsDefault: number;
  equitySampleMsDefault: number;
  persistDefault: boolean;
  symbol: string;
}): string {
  const maxPoints = Number.isFinite(opts.maxEquityPointsDefault)
    ? Math.max(200, Math.min(20_000, Math.floor(opts.maxEquityPointsDefault)))
    : 5_000;
  const sampleMs = Number.isFinite(opts.equitySampleMsDefault)
    ? Math.max(250, Math.min(60_000, Math.floor(opts.equitySampleMsDefault)))
    : 2_000;
  const persist = opts.persistDefault ? "true" : "false";
  const symbol = String(opts.symbol || "BTC-USD").replace(/[^a-zA-Z0-9_-]/g, "_");

  return [
    `const DEFAULT_MAX_EQUITY_POINTS = ${maxPoints};`,
    `const DEFAULT_EQUITY_SAMPLE_MS = ${sampleMs};`,
    `const DEFAULT_PERSIST_EQUITY_SERIES = ${persist};`,
    `const DEFAULT_EQUITY_STORAGE_KEY = ${JSON.stringify(`revx_equity_series_${symbol}`)};`,
    "",
    "function eqNumber(value, fallback) {",
    "  const parsed = Number(value);",
    "  if (Number.isFinite(parsed)) return parsed;",
    "  const fb = Number(fallback);",
    "  return Number.isFinite(fb) ? fb : 0;",
    "}",
    "",
    "function eqNormalizeMaxPoints(v) {",
    "  const parsed = Number(v);",
    "  if (!Number.isFinite(parsed)) return DEFAULT_MAX_EQUITY_POINTS;",
    "  return Math.max(200, Math.min(20000, Math.floor(parsed)));",
    "}",
    "",
    "function eqNormalizeSampleMs(v) {",
    "  const parsed = Number(v);",
    "  if (!Number.isFinite(parsed)) return DEFAULT_EQUITY_SAMPLE_MS;",
    "  return Math.max(250, Math.min(60000, Math.floor(parsed)));",
    "}",
    "",
    "function eqAssetCode(row) {",
    "  if (!row || typeof row !== 'object') return '';",
    "  const direct = [row.asset, row.currency, row.code, row.ccy, row.symbol];",
    "  for (const value of direct) {",
    "    if (typeof value === 'string' && value.trim().length > 0) return value.trim().toUpperCase();",
    "  }",
    "  return '';",
    "}",
    "",
    "function eqFindBalanceRow(rows, aliases) {",
    "  const list = Array.isArray(rows) ? rows : [];",
    "  const wanted = new Set((Array.isArray(aliases) ? aliases : []).map((a) => String(a).toUpperCase()));",
    "  for (const row of list) {",
    "    if (wanted.has(eqAssetCode(row))) return row;",
    "  }",
    "  return null;",
    "}",
    "",
    "function eqReadPersistedSeries(key) {",
    "  try {",
    "    if (typeof localStorage === 'undefined') return [];",
    "    const raw = localStorage.getItem(key);",
    "    if (!raw) return [];",
    "    const parsed = JSON.parse(raw);",
    "    if (!Array.isArray(parsed)) return [];",
    "    return parsed",
    "      .filter((row) => row && typeof row === 'object')",
    "      .filter((row) => Number.isFinite(Number(row.ts)) && Number.isFinite(Number(row.mid)))",
    "      .filter((row) => Number.isFinite(Number(row.equityUsd)) && Number.isFinite(Number(row.equityBtc)))",
    "      .filter((row) => Number.isFinite(Number(row.usd_total)) && Number.isFinite(Number(row.btc_total)))",
    "      .slice(-DEFAULT_MAX_EQUITY_POINTS);",
    "  } catch {",
    "    return [];",
    "  }",
    "}",
    "",
    "function eqWritePersistedSeries(key, series) {",
    "  try {",
    "    if (typeof localStorage === 'undefined') return;",
    "    localStorage.setItem(key, JSON.stringify(Array.isArray(series) ? series : []));",
    "  } catch {",
    "    // ignore localStorage errors",
    "  }",
    "}",
    "",
    "function eqClearPersistedSeries(key) {",
    "  try {",
    "    if (typeof localStorage === 'undefined') return;",
    "    localStorage.removeItem(key);",
    "  } catch {",
    "    // ignore localStorage errors",
    "  }",
    "}",
    "",
    "function useEquitySeries(payload, currentSeries, opts) {",
    "  const next = Array.isArray(currentSeries) ? currentSeries.slice() : [];",
    "  if (!payload || typeof payload !== 'object') return next;",
    "",
    "  const sampleMs = eqNormalizeSampleMs(opts && opts.sampleMs);",
    "  const maxPoints = eqNormalizeMaxPoints(opts && opts.maxPoints);",
    "",
    "  const tsRaw = eqNumber(payload.ts, Date.now());",
    "  const mid = eqNumber(payload.ticker && payload.ticker.mid, 0);",
    "  if (!(mid > 0)) return next;",
    "",
    "  const balances = Array.isArray(payload.balances) ? payload.balances : [];",
    "  const usdRow = eqFindBalanceRow(balances, ['USD', 'USDC']);",
    "  const btcRow = eqFindBalanceRow(balances, ['BTC', 'XBT']);",
    "",
    "  const usd_total = eqNumber(usdRow && usdRow.total, 0);",
    "  const usd_free = eqNumber(usdRow && usdRow.free, 0);",
    "  const btc_total = eqNumber(btcRow && btcRow.total, 0);",
    "  const btc_free = eqNumber(btcRow && btcRow.free, 0);",
    "",
    "  const bucketTs = Math.floor(tsRaw / sampleMs) * sampleMs;",
    "  const last = next.length > 0 ? next[next.length - 1] : null;",
    "  if (last && !(bucketTs > eqNumber(last.ts, 0))) {",
    "    return next;",
    "  }",
    "",
    "  next.push({",
    "    ts: bucketTs,",
    "    mid,",
    "    equityUsd: usd_total + btc_total * mid,",
    "    equityBtc: btc_total + usd_total / mid,",
    "    usd_total,",
    "    usd_free,",
    "    btc_total,",
    "    btc_free,",
    "    btcNotionalUsd: btc_total * mid",
    "  });",
    "",
    "  const trimmed = next.length > maxPoints ? next.slice(next.length - maxPoints) : next;",
    "  if (opts && opts.persist === true) {",
    "    eqWritePersistedSeries(opts.storageKey || DEFAULT_EQUITY_STORAGE_KEY, trimmed);",
    "  }",
    "",
    "  return trimmed;",
    "}",
    ""
  ].join("\n");
}
